version: '2.1'

services:
  k8s-node-example:
    image: k8s-node-example
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js