apiVersion: v1
kind: Service
metadata:
  name: k8s-node-example
  labels:
    app: k8s-node-example
spec:
  selector:
    app: k8s-node-example
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  externalIPs:
    - 10.16.128.1
  type: NodePort
